import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { FormBuilder, FormGroup, ReactiveFormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { Router } from '@angular/router';

interface Station {
  code: string;
  name: string;
  place: string;
}

@Component({
  selector: 'app-booking-ticket',
  standalone: true,
  imports: [RouterLink, CommonModule,ReactiveFormsModule],
  templateUrl: './booking-ticket.component.html',
  styleUrl: './booking-ticket.component.scss',
})
export class BookingTicketComponent {
  stations: Station[] = [
    { code: 'CNB', name: 'Kanpur Central', place: 'Kanpur' },
    {
      code: 'DDU',
      name: 'Pt. Deen Dayal Upadhyaya Junction',
      place: 'Chandauli',
    },
    { code: 'JHS', name: 'Jhansi Junction', place: 'Jhansi' },
    {
      code: 'VGLJ',
      name: 'Virangana Lakshmibai Jhansi Junction',
      place: 'Jhansi',
    },
    { code: 'LKO', name: 'Lucknow Charbagh NR', place: 'Lucknow' },
    { code: 'PRYJ', name: 'Prayagraj Junction', place: 'Prayagraj' },
    { code: 'MTJ', name: 'Mathura Junction', place: 'Mathura' },
    { code: 'GZB', name: 'Ghaziabad Junction', place: 'Ghaziabad' },
    { code: 'BSB', name: 'Varanasi Junction', place: 'Varanasi' },
    { code: 'AGC', name: 'Agra Cantonment', place: 'Agra' },
    { code: 'GKP', name: 'Gorakhpur Junction', place: 'Gorakhpur' },
    { code: 'LC', name: 'Lucknow City', place: 'Lucknow' },
    { code: 'LJN', name: 'Lucknow Junction', place: 'Lucknow' },
    { code: 'MB', name: 'Moradabad Junction', place: 'Moradabad' },
    { code: 'BE', name: 'Bareilly Junction', place: 'Bareilly' },
    { code: 'GD', name: 'Gonda Junction', place: 'Gonda' },
    { code: 'SRE', name: 'Saharanpur Junction', place: 'Saharanpur' },
    { code: 'BST', name: 'Basti', place: 'Basti' },
    { code: 'TDL', name: 'Tundla Junction', place: 'Tundla' },
    { code: 'PCOI', name: 'Prayagraj Chheoki Junction', place: 'Prayagraj' },
    { code: 'SPN', name: 'Shahjahanpur', place: 'Shahjehanpur' },
    { code: 'DEOS', name: 'Deoria Sadar', place: 'Deoria Sadar' },
    { code: 'MZP', name: 'Mirzapur', place: 'Mirzapur' },
    { code: 'ALJN', name: 'Aligarh Junction', place: 'Aligarh' },
    { code: 'SLN', name: 'Sultanpur Junction', place: 'Sultanpur' },
    { code: 'HRI', name: 'Hardoi', place: 'Hardoi' },
    { code: 'BUI', name: 'Ballia', place: 'Ballia' },
    { code: 'ETW', name: 'Etawah Junction', place: 'Etawah' },
    { code: 'FD', name: 'Faizabad Junction', place: 'Faizabad' },
    { code: 'SHG', name: 'Shahganj Junction', place: 'Shahganj' },
    { code: 'RBL', name: 'Rae Bareli Junction', place: 'Rae Bareli' },
    { code: 'JNU', name: 'Jaunpur Junction', place: 'Jaunpur' },
    {
      code: 'MBDP',
      name: 'Maa Belha Devi Dham Pratapgarh Junction',
      place: 'Partapgarh',
    },
    { code: 'PBH', name: 'Pratapgarh Junction', place: 'Partapgarh' },
    { code: 'MAU', name: 'Mau Junction', place: 'Mau' },
    { code: 'MTC', name: 'Meerut City Junction', place: 'Meerut' },
    { code: 'AF', name: 'Agra Fort', place: 'Agra Fort' },
    { code: 'ABP', name: 'Akbarpur Junction', place: 'Akbarpur' },
    { code: 'MOZ', name: 'Muzaffarnagar', place: 'Muzaffarnagar' },
    { code: 'BNDA', name: 'Banda Junction', place: 'Banda' },
    { code: 'AMH', name: 'Azamgarh', place: 'Azamgarh' },
    { code: 'BSBS', name: 'Banaras', place: 'Manduadih' },
    { code: 'MUV', name: 'Manduadih', place: 'Manduadih' },
    { code: 'BBK', name: 'Barabanki Junction', place: 'Barabanki' },
    { code: 'MKP', name: 'Manikpur Junction', place: 'Manikpur' },
    { code: 'LAR', name: 'Lalitpur', place: 'Lalitpur' },
    { code: 'ON', name: 'Unnao Junction', place: 'Unnao' },
    { code: 'HPU', name: 'Hapur Junction', place: 'Hapur' },
    { code: 'DLN', name: 'Dildarnagar Junction', place: 'Dildarnagar' },
    { code: 'FGG', name: 'Farrukhabad Junction', place: 'Farrukhabad' },
    { code: 'PRG', name: 'Purwa', place: 'Purwa' },
    { code: 'RBL', name: 'Rae Bareli Junction', place: 'Rae Bareli' },
    { code: 'RURA', name: 'Rura', place: 'Rura' },
    { code: 'KNS', name: 'Kanpur Anwarganj', place: 'Kanpur' },
    { code: 'DRGJ', name: 'Daryabad', place: 'Barabanki' },
    { code: 'FBD', name: 'Farrukhabad', place: 'Farrukhabad' },
    { code: 'AE', name: 'Aunrihar Junction', place: 'Aunrihar' },
    { code: 'SV', name: 'Sahibganj', place: 'Sahibganj' },
    { code: 'KKDE', name: 'Khalilabad', place: 'Sant Kabir Nagar' },
    { code: 'FPB', name: 'Faridpur', place: 'Bareilly' },
    { code: 'RY', name: 'Rayyan', place: 'Amethi' },
    { code: 'JOP', name: 'Jaunpur City', place: 'Jaunpur' },
    { code: 'KLD', name: 'Khalilabad', place: 'Sant Kabir Nagar' },
    { code: 'FGD', name: 'Faizabad City', place: 'Faizabad' },
    { code: 'KLAR', name: 'Kulha', place: 'Sultanpur' },
    { code: 'CKTD', name: 'Chowka Ghat', place: 'Gorakhpur' },
    { code: 'PBH', name: 'Pilibhit Junction', place: 'Pilibhit' },
    { code: 'MBP', name: 'Mubarakpur', place: 'Azamgarh' },
    { code: 'MGW', name: 'Mihinpurwa', place: 'Mihinpurwa' },
    { code: 'SPN', name: 'Sathiaon', place: 'Ballia' },
    { code: 'NSP', name: 'Naugarh', place: 'Siddharthnagar' },
    { code: 'DY', name: 'Daryabad', place: 'Barabanki' },
    { code: 'PTF', name: 'Patharia', place: 'Bareilly' },
    { code: 'SKW', name: 'Sikandarpur', place: 'Ballia' },
    { code: 'BSC', name: 'Bisalpur', place: 'Bisalpur' },
    { code: 'BLNR', name: 'Baleni', place: 'Sitapur' },
    { code: 'BSR', name: 'Basti', place: 'Basti' },
    { code: 'ABP', name: 'Ambiapur', place: 'Sultanpur' },
    { code: 'MWUE', name: 'Mallanwan', place: 'Sitapur' },
    { code: 'SAW', name: 'Sonakhan', place: 'Unnao' },
    { code: 'RM', name: 'Rudauli', place: 'Faizabad' },
    { code: 'GNG', name: 'Gangauli', place: 'Azamgarh' },
    { code: 'MMY', name: 'Muhammadabad', place: 'Mau' },
    { code: 'CCG', name: 'Cutchery Ghat', place: 'Gorakhpur' },
    { code: 'STP', name: 'Shahganj', place: 'Jaunpur' },
    { code: 'MJF', name: 'Muhammadpur', place: 'Faizabad' },
    { code: 'BRPT', name: 'Baripura', place: 'Sultanpur' },
    { code: 'SKN', name: 'Shrikrishnanagar', place: 'Maharajganj' },
    { code: 'AJH', name: 'Ajgain', place: 'Kanpur' },
    { code: 'BTK', name: 'Baghauli', place: 'Kanpur' },
    { code: 'TBR', name: 'Tribeni', place: 'Lucknow' },
    { code: 'GAA', name: 'Girdharpur', place: 'Lucknow' },
    { code: 'SBK', name: 'Sibai', place: 'Lucknow' },
    { code: 'MDP', name: 'Munderwa', place: 'Basti' },
    { code: 'KTE', name: 'Katra', place: 'Sultanpur' },
    { code: 'DRD', name: 'Duraundha Junction', place: 'Deoria' },
    { code: 'SFG', name: 'Sarai Gopal', place: 'Kanpur' },
    { code: 'BPB', name: 'Bhadanpur', place: 'Sultanpur' },
    { code: 'MND', name: 'Mandhana Junction', place: 'Kanpur' },
    { code: 'RYG', name: 'Rudain', place: 'Amethi' },
    { code: 'SRY', name: 'Sareni', place: 'Raebareli' },
    { code: 'RYS', name: 'Rae Bareli Satellite', place: 'Rae Bareli' },
    { code: 'AKS', name: 'Akbarganj', place: 'Lucknow' },
    { code: 'GMU', name: 'Garhi Manikpur', place: 'Pratapgarh' },
    { code: 'JLN', name: 'Jalalpur', place: 'Ambedkarnagar' },
    { code: 'BAA', name: 'Baragaon', place: 'Lucknow' },
    { code: 'GFN', name: 'Gursahaiganj', place: 'Kannauj' },
    { code: 'BQW', name: 'Bargawan', place: 'Kannauj' },
    { code: 'NSZ', name: 'Nisoi', place: 'Hardoi' },
    { code: 'JRK', name: 'Jharkhand', place: 'Hardoi' },
    { code: 'SDAM', name: 'Sudamapur', place: 'Hardoi' },
    { code: 'RTGN', name: 'Raitaiganj', place: 'Barabanki' },
    { code: 'URP', name: 'Unchahar Junction', place: 'Raebareli' },
    { code: 'LBA', name: 'Lalgaunj', place: 'Raebareli' },
    { code: 'OKA', name: 'Unchaulia', place: 'Raebareli' },
    { code: 'DOA', name: 'Daryapur', place: 'Raebareli' },
    { code: 'RYA', name: 'Rahimanpur', place: 'Raebareli' },
    { code: 'DRP', name: 'Daryapur', place: 'Raebareli' },
    { code: 'BAQ', name: 'Balamau Junction', place: 'Hardoi' },
    { code: 'JFG', name: 'Jarauna', place: 'Barabanki' },
    { code: 'RD', name: 'Reoti Bahora Khera', place: 'Barabanki' },
    { code: 'LCN', name: 'Lucknow City Junction', place: 'Lucknow' },
    { code: 'AVP', name: 'Aman Vadi', place: 'Sitapur' },
    { code: 'ORW', name: 'Orwan', place: 'Sitapur' },
    { code: 'LTN', name: 'Lahartara', place: 'Varanasi' },
    { code: 'SLE', name: 'Salempur Junction', place: 'Deoria' },
    { code: 'BEM', name: 'Basantapur', place: 'Sultanpur' },
    { code: 'CSA', name: 'Chauri Chaura', place: 'Gorakhpur' },
    { code: 'LLPR', name: 'Lalpur', place: 'Sitapur' },
    { code: 'SGG', name: 'Saktesgarh', place: 'Barabanki' },
    { code: 'TRE', name: 'Tirathrajpur', place: 'Barabanki' },
    { code: 'FPA', name: 'Farhedi Junction', place: 'Hardoi' },
    { code: 'GNGD', name: 'Ganga Dham', place: 'Lucknow' },
    { code: 'BSX', name: 'Barsathi', place: 'Lucknow' },
    { code: 'SMZ', name: 'Salarpur', place: 'Lucknow' },
    { code: 'BASK', name: 'Baiswara Junction', place: 'Lucknow' },
    { code: 'BKT', name: 'Bakhsha', place: 'Lucknow' },
    { code: 'AGY', name: 'Agauna', place: 'Gonda' },
    { code: 'GOM', name: 'Gomati Nagar', place: 'Lucknow' },
    { code: 'NRS', name: 'Nihalgarh', place: 'Sultanpur' },
    { code: 'PLP', name: 'Pulaha', place: 'Sultanpur' },
    { code: 'RSP', name: 'Rasull', place: 'Sultanpur' },
    { code: 'SFR', name: 'Shivnagar', place: 'Sultanpur' },
    { code: 'SVZ', name: 'Shivnagar', place: 'Sultanpur' },
    { code: 'YDV', name: 'Yadvendranagar', place: 'Sultanpur' },
    { code: 'BRY', name: 'Barua', place: 'Sultanpur' },
    { code: 'TSB', name: 'Tulsipur', place: 'Balrampur' },
    { code: 'PAA', name: 'Pakaha', place: 'Kanpur' },
    { code: 'BSQP', name: 'Baiswara Junction', place: 'Kanpur' },
    { code: 'MNDL', name: 'Mandawali-Chanderpal', place: 'Lucknow' },
    { code: 'APX', name: 'Atwa Muthia Halt', place: 'Lucknow' },
    { code: 'SMJ', name: 'Shamshabad Muhammadpur', place: 'Unnao' },
    { code: 'JDV', name: 'Jagdishpur', place: 'Amethi' },
    { code: 'MDNR', name: 'Madanpur', place: 'Amethi' },
    { code: 'GKT', name: 'Garh Kunta Halt', place: 'Raebareli' },
    { code: 'BGZ', name: 'Baghauli', place: 'Kanpur' },
    { code: 'MKM', name: 'Mankapur Junction', place: 'Gonda' },
    { code: 'NAW', name: 'Nawabganj Gonda', place: 'Gonda' },
    { code: 'GOVR', name: 'Goverdhan', place: 'Mathura' },
    { code: 'HSR', name: 'Hasanpur Road', place: 'Amroha' },
    { code: 'MJG', name: 'Marajganj', place: 'Gonda' },
    { code: 'PHV', name: 'Pora', place: 'Hapur' },
    { code: 'MJDP', name: 'Majhagawan', place: 'Satna' },
    { code: 'CGN', name: 'Chirgaon', place: 'Jhansi' },
    { code: 'SPDC', name: 'Shivpura dehat', place: 'Jhansi' },
    { code: 'DAWN', name: 'Dauna Badshahpur', place: 'Kanpur' },
    { code: 'GBM', name: 'Garhmuktesar', place: 'Ghaziabad' },
    { code: 'HSI', name: 'Hansi', place: 'Ghaziabad' },
    { code: 'BPDR', name: 'Bhader', place: 'Ghaziabad' },
    { code: 'MDNR', name: 'Madanpur', place: 'Amethi' },
    { code: 'KLA', name: 'Khanalampura', place: 'Unnao' },
    { code: 'SWC', name: 'Sewapuri', place: 'Varanasi' },
    { code: 'GOY', name: 'Govindpuri Junction', place: 'Kanpur' },
    { code: 'PYGS', name: 'Payagpur', place: 'Bahraich' },
    { code: 'MKH', name: 'Manikalan Halt', place: 'Jhansi' },
  ];
  stationsTo: Station[] = [
    { code: 'CNB', name: 'Kanpur Central', place: 'Kanpur' },
    {
      code: 'DDU',
      name: 'Pt. Deen Dayal Upadhyaya Junction',
      place: 'Chandauli',
    },
    { code: 'JHS', name: 'Jhansi Junction', place: 'Jhansi' },
    {
      code: 'VGLJ',
      name: 'Virangana Lakshmibai Jhansi Junction',
      place: 'Jhansi',
    },
    { code: 'LKO', name: 'Lucknow Charbagh NR', place: 'Lucknow' },
    { code: 'PRYJ', name: 'Prayagraj Junction', place: 'Prayagraj' },
    { code: 'MTJ', name: 'Mathura Junction', place: 'Mathura' },
    { code: 'GZB', name: 'Ghaziabad Junction', place: 'Ghaziabad' },
    { code: 'BSB', name: 'Varanasi Junction', place: 'Varanasi' },
    { code: 'AGC', name: 'Agra Cantonment', place: 'Agra' },
    { code: 'GKP', name: 'Gorakhpur Junction', place: 'Gorakhpur' },
    { code: 'LC', name: 'Lucknow City', place: 'Lucknow' },
    { code: 'LJN', name: 'Lucknow Junction', place: 'Lucknow' },
    { code: 'MB', name: 'Moradabad Junction', place: 'Moradabad' },
    { code: 'BE', name: 'Bareilly Junction', place: 'Bareilly' },
    { code: 'GD', name: 'Gonda Junction', place: 'Gonda' },
    { code: 'SRE', name: 'Saharanpur Junction', place: 'Saharanpur' },
    { code: 'BST', name: 'Basti', place: 'Basti' },
    { code: 'TDL', name: 'Tundla Junction', place: 'Tundla' },
    { code: 'PCOI', name: 'Prayagraj Chheoki Junction', place: 'Prayagraj' },
    { code: 'SPN', name: 'Shahjahanpur', place: 'Shahjehanpur' },
    { code: 'DEOS', name: 'Deoria Sadar', place: 'Deoria Sadar' },
    { code: 'MZP', name: 'Mirzapur', place: 'Mirzapur' },
    { code: 'ALJN', name: 'Aligarh Junction', place: 'Aligarh' },
    { code: 'SLN', name: 'Sultanpur Junction', place: 'Sultanpur' },
    { code: 'HRI', name: 'Hardoi', place: 'Hardoi' },
    { code: 'BUI', name: 'Ballia', place: 'Ballia' },
    { code: 'ETW', name: 'Etawah Junction', place: 'Etawah' },
    { code: 'FD', name: 'Faizabad Junction', place: 'Faizabad' },
    { code: 'SHG', name: 'Shahganj Junction', place: 'Shahganj' },
    { code: 'RBL', name: 'Rae Bareli Junction', place: 'Rae Bareli' },
    { code: 'JNU', name: 'Jaunpur Junction', place: 'Jaunpur' },
    {
      code: 'MBDP',
      name: 'Maa Belha Devi Dham Pratapgarh Junction',
      place: 'Partapgarh',
    },
    { code: 'PBH', name: 'Pratapgarh Junction', place: 'Partapgarh' },
    { code: 'MAU', name: 'Mau Junction', place: 'Mau' },
    { code: 'MTC', name: 'Meerut City Junction', place: 'Meerut' },
    { code: 'AF', name: 'Agra Fort', place: 'Agra Fort' },
    { code: 'ABP', name: 'Akbarpur Junction', place: 'Akbarpur' },
    { code: 'MOZ', name: 'Muzaffarnagar', place: 'Muzaffarnagar' },
    { code: 'BNDA', name: 'Banda Junction', place: 'Banda' },
    { code: 'AMH', name: 'Azamgarh', place: 'Azamgarh' },
    { code: 'BSBS', name: 'Banaras', place: 'Manduadih' },
    { code: 'MUV', name: 'Manduadih', place: 'Manduadih' },
    { code: 'BBK', name: 'Barabanki Junction', place: 'Barabanki' },
    { code: 'MKP', name: 'Manikpur Junction', place: 'Manikpur' },
    { code: 'LAR', name: 'Lalitpur', place: 'Lalitpur' },
    { code: 'ON', name: 'Unnao Junction', place: 'Unnao' },
    { code: 'HPU', name: 'Hapur Junction', place: 'Hapur' },
    { code: 'DLN', name: 'Dildarnagar Junction', place: 'Dildarnagar' },
    { code: 'FGG', name: 'Farrukhabad Junction', place: 'Farrukhabad' },
    { code: 'PRG', name: 'Purwa', place: 'Purwa' },
    { code: 'RBL', name: 'Rae Bareli Junction', place: 'Rae Bareli' },
    { code: 'RURA', name: 'Rura', place: 'Rura' },
    { code: 'KNS', name: 'Kanpur Anwarganj', place: 'Kanpur' },
    { code: 'DRGJ', name: 'Daryabad', place: 'Barabanki' },
    { code: 'FBD', name: 'Farrukhabad', place: 'Farrukhabad' },
    { code: 'AE', name: 'Aunrihar Junction', place: 'Aunrihar' },
    { code: 'SV', name: 'Sahibganj', place: 'Sahibganj' },
    { code: 'KKDE', name: 'Khalilabad', place: 'Sant Kabir Nagar' },
    { code: 'FPB', name: 'Faridpur', place: 'Bareilly' },
    { code: 'RY', name: 'Rayyan', place: 'Amethi' },
    { code: 'JOP', name: 'Jaunpur City', place: 'Jaunpur' },
    { code: 'KLD', name: 'Khalilabad', place: 'Sant Kabir Nagar' },
    { code: 'FGD', name: 'Faizabad City', place: 'Faizabad' },
    { code: 'KLAR', name: 'Kulha', place: 'Sultanpur' },
    { code: 'CKTD', name: 'Chowka Ghat', place: 'Gorakhpur' },
    { code: 'PBH', name: 'Pilibhit Junction', place: 'Pilibhit' },
    { code: 'MBP', name: 'Mubarakpur', place: 'Azamgarh' },
    { code: 'MGW', name: 'Mihinpurwa', place: 'Mihinpurwa' },
    { code: 'SPN', name: 'Sathiaon', place: 'Ballia' },
    { code: 'NSP', name: 'Naugarh', place: 'Siddharthnagar' },
    { code: 'DY', name: 'Daryabad', place: 'Barabanki' },
    { code: 'PTF', name: 'Patharia', place: 'Bareilly' },
    { code: 'SKW', name: 'Sikandarpur', place: 'Ballia' },
    { code: 'BSC', name: 'Bisalpur', place: 'Bisalpur' },
    { code: 'BLNR', name: 'Baleni', place: 'Sitapur' },
    { code: 'BSR', name: 'Basti', place: 'Basti' },
    { code: 'ABP', name: 'Ambiapur', place: 'Sultanpur' },
    { code: 'MWUE', name: 'Mallanwan', place: 'Sitapur' },
    { code: 'SAW', name: 'Sonakhan', place: 'Unnao' },
    { code: 'RM', name: 'Rudauli', place: 'Faizabad' },
    { code: 'GNG', name: 'Gangauli', place: 'Azamgarh' },
    { code: 'MMY', name: 'Muhammadabad', place: 'Mau' },
    { code: 'CCG', name: 'Cutchery Ghat', place: 'Gorakhpur' },
    { code: 'STP', name: 'Shahganj', place: 'Jaunpur' },
    { code: 'MJF', name: 'Muhammadpur', place: 'Faizabad' },
    { code: 'BRPT', name: 'Baripura', place: 'Sultanpur' },
    { code: 'SKN', name: 'Shrikrishnanagar', place: 'Maharajganj' },
    { code: 'AJH', name: 'Ajgain', place: 'Kanpur' },
    { code: 'BTK', name: 'Baghauli', place: 'Kanpur' },
    { code: 'TBR', name: 'Tribeni', place: 'Lucknow' },
    { code: 'GAA', name: 'Girdharpur', place: 'Lucknow' },
    { code: 'SBK', name: 'Sibai', place: 'Lucknow' },
    { code: 'MDP', name: 'Munderwa', place: 'Basti' },
    { code: 'KTE', name: 'Katra', place: 'Sultanpur' },
    { code: 'DRD', name: 'Duraundha Junction', place: 'Deoria' },
    { code: 'SFG', name: 'Sarai Gopal', place: 'Kanpur' },
    { code: 'BPB', name: 'Bhadanpur', place: 'Sultanpur' },
    { code: 'MND', name: 'Mandhana Junction', place: 'Kanpur' },
    { code: 'RYG', name: 'Rudain', place: 'Amethi' },
    { code: 'SRY', name: 'Sareni', place: 'Raebareli' },
    { code: 'RYS', name: 'Rae Bareli Satellite', place: 'Rae Bareli' },
    { code: 'AKS', name: 'Akbarganj', place: 'Lucknow' },
    { code: 'GMU', name: 'Garhi Manikpur', place: 'Pratapgarh' },
    { code: 'JLN', name: 'Jalalpur', place: 'Ambedkarnagar' },
    { code: 'BAA', name: 'Baragaon', place: 'Lucknow' },
    { code: 'GFN', name: 'Gursahaiganj', place: 'Kannauj' },
    { code: 'BQW', name: 'Bargawan', place: 'Kannauj' },
    { code: 'NSZ', name: 'Nisoi', place: 'Hardoi' },
    { code: 'JRK', name: 'Jharkhand', place: 'Hardoi' },
    { code: 'SDAM', name: 'Sudamapur', place: 'Hardoi' },
    { code: 'RTGN', name: 'Raitaiganj', place: 'Barabanki' },
    { code: 'URP', name: 'Unchahar Junction', place: 'Raebareli' },
    { code: 'LBA', name: 'Lalgaunj', place: 'Raebareli' },
    { code: 'OKA', name: 'Unchaulia', place: 'Raebareli' },
    { code: 'DOA', name: 'Daryapur', place: 'Raebareli' },
    { code: 'RYA', name: 'Rahimanpur', place: 'Raebareli' },
    { code: 'DRP', name: 'Daryapur', place: 'Raebareli' },
    { code: 'BAQ', name: 'Balamau Junction', place: 'Hardoi' },
    { code: 'JFG', name: 'Jarauna', place: 'Barabanki' },
    { code: 'RD', name: 'Reoti Bahora Khera', place: 'Barabanki' },
    { code: 'LCN', name: 'Lucknow City Junction', place: 'Lucknow' },
    { code: 'AVP', name: 'Aman Vadi', place: 'Sitapur' },
    { code: 'ORW', name: 'Orwan', place: 'Sitapur' },
    { code: 'LTN', name: 'Lahartara', place: 'Varanasi' },
    { code: 'SLE', name: 'Salempur Junction', place: 'Deoria' },
    { code: 'BEM', name: 'Basantapur', place: 'Sultanpur' },
    { code: 'CSA', name: 'Chauri Chaura', place: 'Gorakhpur' },
    { code: 'LLPR', name: 'Lalpur', place: 'Sitapur' },
    { code: 'SGG', name: 'Saktesgarh', place: 'Barabanki' },
    { code: 'TRE', name: 'Tirathrajpur', place: 'Barabanki' },
    { code: 'FPA', name: 'Farhedi Junction', place: 'Hardoi' },
    { code: 'GNGD', name: 'Ganga Dham', place: 'Lucknow' },
    { code: 'BSX', name: 'Barsathi', place: 'Lucknow' },
    { code: 'SMZ', name: 'Salarpur', place: 'Lucknow' },
    { code: 'BASK', name: 'Baiswara Junction', place: 'Lucknow' },
    { code: 'BKT', name: 'Bakhsha', place: 'Lucknow' },
    { code: 'AGY', name: 'Agauna', place: 'Gonda' },
    { code: 'GOM', name: 'Gomati Nagar', place: 'Lucknow' },
    { code: 'NRS', name: 'Nihalgarh', place: 'Sultanpur' },
    { code: 'PLP', name: 'Pulaha', place: 'Sultanpur' },
    { code: 'RSP', name: 'Rasull', place: 'Sultanpur' },
    { code: 'SFR', name: 'Shivnagar', place: 'Sultanpur' },
    { code: 'SVZ', name: 'Shivnagar', place: 'Sultanpur' },
    { code: 'YDV', name: 'Yadvendranagar', place: 'Sultanpur' },
    { code: 'BRY', name: 'Barua', place: 'Sultanpur' },
    { code: 'TSB', name: 'Tulsipur', place: 'Balrampur' },
    { code: 'PAA', name: 'Pakaha', place: 'Kanpur' },
    { code: 'BSQP', name: 'Baiswara Junction', place: 'Kanpur' },
    { code: 'MNDL', name: 'Mandawali-Chanderpal', place: 'Lucknow' },
    { code: 'APX', name: 'Atwa Muthia Halt', place: 'Lucknow' },
    { code: 'SMJ', name: 'Shamshabad Muhammadpur', place: 'Unnao' },
    { code: 'JDV', name: 'Jagdishpur', place: 'Amethi' },
    { code: 'MDNR', name: 'Madanpur', place: 'Amethi' },
    { code: 'GKT', name: 'Garh Kunta Halt', place: 'Raebareli' },
    { code: 'BGZ', name: 'Baghauli', place: 'Kanpur' },
    { code: 'MKM', name: 'Mankapur Junction', place: 'Gonda' },
    { code: 'NAW', name: 'Nawabganj Gonda', place: 'Gonda' },
    { code: 'GOVR', name: 'Goverdhan', place: 'Mathura' },
    { code: 'HSR', name: 'Hasanpur Road', place: 'Amroha' },
    { code: 'MJG', name: 'Marajganj', place: 'Gonda' },
    { code: 'PHV', name: 'Pora', place: 'Hapur' },
    { code: 'MJDP', name: 'Majhagawan', place: 'Satna' },
    { code: 'CGN', name: 'Chirgaon', place: 'Jhansi' },
    { code: 'SPDC', name: 'Shivpura dehat', place: 'Jhansi' },
    { code: 'DAWN', name: 'Dauna Badshahpur', place: 'Kanpur' },
    { code: 'GBM', name: 'Garhmuktesar', place: 'Ghaziabad' },
    { code: 'HSI', name: 'Hansi', place: 'Ghaziabad' },
    { code: 'BPDR', name: 'Bhader', place: 'Ghaziabad' },
    { code: 'MDNR', name: 'Madanpur', place: 'Amethi' },
    { code: 'KLA', name: 'Khanalampura', place: 'Unnao' },
    { code: 'SWC', name: 'Sewapuri', place: 'Varanasi' },
    { code: 'GOY', name: 'Govindpuri Junction', place: 'Kanpur' },
    { code: 'PYGS', name: 'Payagpur', place: 'Bahraich' },
    { code: 'MKH', name: 'Manikalan Halt', place: 'Jhansi' },
  ].reverse();

  sheet: any[] = ['All Classes', '1AC', '2AC', '3AC', 'Sleeper Class'];

  typeOfTicket: any[] = [
    'GENERAL',
    'LOWER BERTH/SR.CITIZEN',
    'LADIES',
    'PERSON WITH DISABILITY',
    'DUTY PASS',
    'TATKAL',
    'PREMIUM TATKAL',
  ];
  trackByFn(index:number, stationsTo:Station) {return stationsTo.name;}

  ticketForm!:FormGroup;

  constructor(private fb:FormBuilder, private router:Router){}

  ngOnInit(){
    this.searchTicket();
  }

  searchTicket(){
    this.ticketForm=this.fb.group({
      from:[''],
      to:[''],
      date:[''],
      typeSheet:[''],
      typeCota:['']
    })
  }



  OnsearchTickets(){
    console.log(this.ticketForm.value);
    this.router.navigate(['/ticket-list'])
  }
}
